### ISSUE TITLE
Interactive Features

### ISSUE THREAD

**Issue by jirutka** [grissius/emily-editor#81]
List of interactive features that would be useful.

- [x] ~Insert xref (internal link) to another file in the repository.~#91
    * Show list of files in the repository with interactive filter.
- [X] ~Insert media (image, video, …).~ #91 #92
    * Show list of files in the repository with interactive filter.
    * Allow to add a media file to the repository and insert image/video/audio/… directive to the page in single/few step(s).
    * Maybe also some form with some common attributes that can be specified (e.g. size).
- [x] ~Create/edit table.~ #93
    * Some support for creating/editing larger tables (needs some brainstorm to specify details).
- [x] ~Optional formatting buttons for noobs (similar to the comment editor on GitHub).~  #55 duplicate

- [X] ~Autocompletion for variable names and identifiers.~ #90

/cc @mmajko

**Comment by grissius** [comment]
Thanks @jirutka for imput. Working on some of them already, but non of them is done at the moment. However I split the features into seperate issues to be able to track them individually.

Closing for now. If any random small feature ideas pop into mind, feel free to reopen and share.
